### PR TITLE
Add audioworklet example

### PR DESCRIPTION
**Pull request by wbamberg**
This is for https://github.com/mdn/content/issues/6426 - the page on "Using AudioWorklet" (https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Using_AudioWorklet) has an example hosted on Glitch, that's broken. Rather than fix the Glitch example, it would be better to move it into this repo (see also https://github.com/mdn/content/pull/6428#pullrequestreview-695290146).

This PR also fixed all the links in this repo's README.

I haven't made any more substantial efforts to improve the example - apart from applying @sideshowbarker 's fix, fixing one unrelated problem with the CSS, and removing some old logging code, I've just copy/pasted it and checked it works.

### CODE REVIEW

**Review by sideshowbarker — APPROVED** [review]

**Comment by sideshowbarker** [comment]
I’d merge, but I don’t have write/push perms here…

**Comment by wbamberg** [comment]
You can see the example running at https://wbamberg.github.io/webaudio-examples/audioworklet/.

**Comment by teoli2003** [comment]
@rumyra, I think you have write access here, can you help them?

**Review by Rumyra — APPROVED** [review]

**Comment by Rumyra** [comment]
I'm going to create a 'Peers' team this week which will give people write access to our highest activity demo repos 👍

**Comment by wbamberg** [comment]
Thanks for merging, Ruth! I filed https://github.com/mdn/content/pull/6819 to update the MDN page.

**Pull request merged**
