### PR TITLE
decodeAudioData w/promise

### PR DESCRIPTION
**Pull request by sidewayss**
A new example page for decodeAudioData() that uses promises, fetch() and async/await. Also cleans up the user interface a tiny bit.
This example goes hand-in-hand with edits I have made to the MDN docs page for decodeAudioData() in this PR: https://github.com/mdn/content/pull/26839
This PR replaces PR #104 in order to use my new GPG key to sign all commits.

### CODE REVIEW

**Comment by sidewayss** [comment]
What the heck?  I signed this one commit, didn't I?
image
That's my GPG key, properly defined in my github.com settings.  It was created 3 days ago, prior to my commit on this branch.  Or is it the creation of this branch that I did prior to setting up the key?  Is that the commit that isn't verified?
Ugh! I am going to create yet another branch from main, commit these changes (including your let->const change), and open a new PR.  If that doesn't work, then I'll have to contact github support to see wtf is going on.  Sorry about this...

**Comment by wbamberg** [comment]
> What the heck? I signed this one commit, didn't I? image That's my GPG key, properly defined in my github.com settings. It was created 3 days ago, prior to my commit on this branch. Or is it the creation of this branch that I did prior to setting up the key? Is that the commit that isn't verified? I can't remember when I created the branch. Ugh! I am going to create yet another branch from main, commit these changes (including your let->const change), and open a new PR. If that doesn't work, then I'll have to contact github support to see wtf is going on. Sorry about this...

Never mind. It is a massive pain getting commit signing working, IIRC.

The only thing I can see is that the email address for the commit (i.e. what I see when I type "git log" on your branch) is "sidewayss@users.noreply.github.com" while the email address GitHub knows about, according to your screenshot, is "sideways@sidewayss.com".

Screen Shot 2023-06-02 at 11 54 13 AM

What is the value given by "git config --get user.email"?

**Comment by sidewayss** [comment]
Sounds like I need to make my github.com email address public, which would align those two, but your github email isn't public and you have verified commits.
Now I'm having trouble starting the gpg-connect-agent for reasons I'm discovering via stackoverflow.  Thanks for your understanding.  This really is way more difficult than it ought to be, but that's standard for this kind of feature, unfortunately.

**Comment by sidewayss** [comment]
I'm closing this after creating #107 with a verified commit.

**Pull request closed without merging**
