### PR TITLE
nits

### PR DESCRIPTION
**Pull request by stoyan**
arrow functions, vars/let/const, ' vs ", tabs vs spaces (I know! In my defence there was a mix of both, so one won :)), less `this`, ran eslint, stylelint

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
These updates look OK to me, thanks @stoyan. @Rumyra , are you happy for me to merge this, or did you have any comments?

**Comment by Rumyra** [comment]
This looks good to me!

I noticed the tabs vs spaces but also noticed one didn't win - I'm curious to know which one @stoyan chose ;)

**Comment by chrisdavidmills** [comment]
Cool, merged. 

Looks like spaces to me, which is good as that's standard MDN style.

**Comment by stoyan** [comment]
well, technically there were more tabs than spaces, I think, but spaces somehow miraculously won :)

Thanks for the code and the articles, @Rumyra, they're priceless!

**Pull request merged**
