### PR TITLE
Adding simple "loading audio..." message.

### PR DESCRIPTION
**Pull request by sanxofon**
In my case, my internet connection is so slow that when I press "play" it takes several seconds that "nothing happens". other desperados of the third world (as me) can appreciate the "loading audio..." message. When loaded, audioURL is shown.

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
Hi there @sanxofon! I think this is a good idea, thanks! I did have some feedback on your code:

* Instead of using `innerHTML`, a better practice is to use `textContent`.
* You are using presentational HTML — `align="center"`. Best practice is to use CSS instead (in the stylesheet, apply `text-align: center` to the paragraph in question)
* I wonder whether the message shown on completion should be something like "Audio sample download finished"? Might be more useful than showing the URL?

**Comment by sanxofon** [comment]
That sounds great. I'll make the changes in my fork and push update later.

**Comment by sanxofon** [comment]
Great! I've updated file with suggestions  best practices.

**Comment by chrisdavidmills** [comment]
It doesn't look like anything's changed. Did you do it on a different PR?

**Comment by sanxofon** [comment]
I don't know what happened, please excuse me. I will try again in a new pull request.

**Comment by chrisdavidmills** [comment]
OK, no worries.

**Pull request closed without merging**
